version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - cyclop
    - dupl
    - errcheck
    - forbidigo
    - funlen
    - goconst
    - gosec
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 10
    dupl:
      threshold: 250
    errcheck:
      exclude-functions:
        - (io.Closer).Close
    funlen:
      lines: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    lll:
      line-length: 160
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
